config/routes.rb
Rorbasic::Application.routes.draw do
get "sign_up" => 'users#new', :as => "sign_up"
resources :users
root :to => "articles#index"
resources :articles
resources :sessions
end

app/models/article.rb
class Article < ActiveRecord::Base
	validates :title, presence: true, length: {minimum: 5}
	validates :content, presence: true, length: {minimum: 10}
	validates :status, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :password
	before_save :add_salt_and_hash
	before_create :add_activation_token
  
  	def add_activation_token
    	self.activation_token = SecureRandom.urlsafe_base64
    	self.activation_status = "not activated"
  	end

	include Humanizer
	require_human_on :create
	
	validates :username, presence: true, uniqueness: true
	validates :email, presence: true, uniqueness: true
	validates :password, presence: true, on: :create, length: {minimum: 5}, confirmation: true


	def add_salt_and_hash
		unless  password.blank?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password,password_salt)
		end	
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :check_current_user

  def current_user
  	current_user ||= User.where("id = ?", session[:user]).first
  end

  def check_current_user
  	if current_user.blank?
  		flash[:error] = "please login first before run the action"
  		redirect_to new_session_url
  	else
  		current_user
  	end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :check_current_user, only: [:new, :create, :edit, :update, :destroy]
  def index
  	@articles = Article.all
  end

  def new
  	@article = Article.new
  end

  def edit
  	@article = Article.find_by_id(params[:id])
  end

  def update
  	@article = Article.find_by_id(params[:id])
  	if @article.update(params_article)
  		flash[:notice] = "Succes Update Records"
  		redirect_to action: 'index'
  	else
  		flash[:error] = "data not valid"
  		render 'edit'
  	end
  end

  def show
  	@article = Article.find_by_id(params[:id])
  end

  def create
  	@article = Article.new(params_article)
  	if @article.save
  		flash[:notice] = "Success Add Records"
  		redirect_to action: 'index'
  	else
  		flash[:error] = "data not valid"
  		render 'new'
  	end
  end

  def destroy
  	@article = Article.find_by_id(params[:id])
  	if @article.destroy
  		flash[:notice] = "Success Delete a Records "
  		redirect_to action: 'index'
  	else
  		flash[:error] = "fails delete a records"
  		redirect_to action: 'index'
  	end
  end

  private
  def params_article
  	params.require(:article).permit(:title, :content, :status)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def create
		username = params[:username]
		password = params[:password]
		user = User.where("username = ?", username).first
		user_password = BCrypt::Engine.hash_secret(password, user.password_salt) unless user.blank?
		if !user_password.blank? and user.password_hash.eql? user_password
			session[:user] = user.id
			flash[:notice] = "Wellcome #{user.username}"
			redirect_to root_url
		else
			params[:username]
			flash[:error] = "Your data not valid"
			render "new"
		end
	end

	def destroy
		session[:user] = nil
		flash[:notice] = "logout session success"
		redirect_to root_url
	end

	def new

	end

	def edit
    user = User.find_by_activation_token(params[:id])
    if user.try(:update,{activation_token: "", activation_status: "active"})
      flash[:notice] = "Your account has active"
      redirect_to root_url
    else
      flash[:notice] = "Wellcome to Rails 4"
      redirect_to root_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
  	@user = User.new
  end

  def edit
  end

    def create
    @user = User.new(params_user)
    if @user.save
      begin 
        ConfirmationMailer.confirm_email("#{@user.email}", @user.activation_token).deliver
      rescue
        flash[:notice] = "activation instruction fails send to your email"
      end
      flash[:notice] = "activation instruction has send to #{@user.email}"
      redirect_to root_url
    else
      flash[:error] = "data not valid"
      render "new"
  	end
  end
  
  private
  	def params_user
  		params.require(:user).permit(:username, :email, :password, :password_confirmation, :humanizer_answer, :humanizer_question_id)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/edit.html.erb
<%= form_for @article do |c| %>
<%= c.label :title %>
<%= c.text_field :title %>
<br/>
<%= c.label :content %>
<%= c.text_area :content, cols: 20, rows: 10 %>
<br/>
<%= c.label :status %>
<%= c.radio_button :status, "active" %>
<%= label :article_status, 'active' %>
<%= c.radio_button :status, "off" %>
<%= label :article_status, 'off' %>
<br/>
<%= c.submit :submit %>
<% end %>

<div>
	<%= link_to "back to index", articles_path %>
</div>

app/views/articles/index.html.erb
<h4>
<% if !current_user %>
<%= link_to 'Login', new_session_path %>
<% else %>
Hello <%= current_user.username %>
<%= link_to 'Logout', session_path(current_user.id), method: "DELETE" %>
<% end %>
</h4>

<% @articles.each do |article| %>
<h3><%= article.title %></h3>
<p><%= article.content.truncate(20) %>
<%= link_to 'read more', article_path(article.id) %></p>
<h5>status : <%= article.status %></h5>
<p><span><%= link_to 'edit', edit_article_path(article.id) %></span> | <span><%= link_to 'delete', article_path(article.id), method: "DELETE", data: {confirm: 'Delete this data ?'} %></span></p>
<hr/>
<% end %>

app/views/articles/new.html.erb
<%= form_for @article do |g| %>
<%= g.label :title %>
<%= g.text_field :title %>
<%= @article.errors[:title].first unless @article.errors[:title].blank? %>
<br/>
<%= g.label :content %>
<%= g.text_area :content, cols: 20, rows: 10 %>
<%= @article.errors[:content].first unless @article.errors[:content].blank? %>
<br/>
<%= g.label :status %>
<%= g.radio_button :status, "active" %>
<%= label :article_status, 'active' %>
<%= g.radio_button :status, "off", :checked => true %>
<%= label :article_status, 'off' %>
<br/>
<%= g.submit :submit %>
<% end %>

app/views/articles/show.html.erb
<h3><%= @article.title %></h3>
<p><%= @article.content %></p>
<p><%= link_to 'back to index', articles_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rorbasic</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<%= form_for @user do |u| %>
<%= u.label :username %>
<%= u.text_field :username %>
<%= @user.errors[:username].first unless @user.errors[:username].blank? %>
<br/>
<%= u.label :email %>
<%= u.text_field :email %>
<%= @user.errors[:email].first unless @user.errors[:email].blank? %>
<br/>
<%= u.label :password %>
<%= u.password_field :password %>
<%= @user.errors[:password].first unless @user.errors[:password].blank? %>
<br/>
<%= u.label :password_confirmation %>
<%= u.password_field :password_confirmation %>
<%= @user.errors[:password_confirmation].first unless @user.errors[:password_confirmation].blank? %>
<br/>
<%= u.label :humanizer_answer, @user.humanizer_question %>
<%= u.text_field :humanizer_answer %>
<%= u.hidden_field :humanizer_question_id %>
<br/>
<%= u.submit %>
<% end %>